### ISSUE TITLE
Does "Disabling" delete my database?

### ISSUE THREAD

**Issue by calebporzio** [tightenco/takeout#109]
Hey Takeout folk, I have a question that may belong as an item in the FAQs or not. (Happy to PR it if it does)

If I `takeout disable mysql`, will it delete my actual database? Like not the docker container/server/thing, but the actual database with all my data.

My guess would be that if I have databases created with the connection and I disable, then I re-enable on that version I would have that data back.

If that is NOT the case, I would really want to know about it. It would make "disable" a REALLY dangerous operation - nah mean?

Anyhow, I'm a Docker newb, but this is my main question

Thanks for this fantastic package!

**Comment by mattstauffer** [comment]
Hey Caleb! 

Your data will stick around! By default almost all of our services use a "volume" to attach your data to for exactly this reason.

So, when you disable the MySQL service, that volume--with all your data in it--will just sit there quietly. And when you re-enable, as long as you attach it to the same volume, all your data will still be there. 

Great idea about documenting this. Thanks!!

**Comment by dela-dels** [comment]
@calebporzio I don't think so. Based on a video I watched of Matt and Jose, the volume on which the MySQL data is on still resides on your computer.

**Comment by mattstauffer** [comment]
(And thanks so much for your kind words!!)

**Comment by calebporzio** [comment]
Got it, perfect!

**Comment by mattstauffer** [comment]
@calebporzio RE This:

> (Happy to PR it if it does)

If you'd like to that'd be great, but if not I'll handle it--your call. Thanks again!

**Comment by calebporzio** [comment]
Done: #110
