### ISSUE TITLE
Declare the entire environment in code

### ISSUE THREAD

**Issue by ju5t** [tightenco/takeout#61]
Takeout looks awesome! Thanks for the presentation.

We're using a similar approach, but instead of Takeout (why wasn't it there yet..) we're using Docker Compose. The biggest reason for Docker Compose is its declarative configuration.

This makes sure everyone is using the same versions. And you can commit it. This has a lot of benefits.

- You don't have to tell which versions your developers need to use.
- Keep track of the dependency versions and test new version when they are released.
- Run Takeout in CI to set up the exact same environment.

It does mean developers use similar passwords, but this could be asked for when Takeout is bootstrapped.

**Comment by voidgraphics** [comment]
I'm a Docker noobie, I admit first and foremost, so take my opinion with a grain of salt.

It sounds like Docker Compose and Takeout would become identical tools, if they both had that feature. Which makes me think, why not just use Docker Compose, then? 

To me, the value in Takeout is that it's an extremely simple tool, where you can get started with Docker by just replacing your local mysql installation with an easily disposable and replaceable one. It fits that niche perfectly, for devs who can't (or don't want to) go full-blown-custom-docker-instances-per-project, but still want to have easily available, disposable services.

That's just my two cents though, and I don't mean to discourage any potential this tool has.

**Comment by mattstauffer** [comment]
Yep, I agree with @voidgraphics--Docker composer is great but it's a bit more complex and higher-cost than Takeout is.

Thanks for bringing up the conversation, @ju5t!

**Comment by ju5t** [comment]
In all fairness, I disagree. I think I didn't explain it properly.

I wouldn't argue that Takeout needs all the features Docker Compose has. I used it to illustrate parts of what I would like to see in Takeout. Version pinning and starting the dependencies all at once makes sense.

```
It sounds like Docker Compose and Takeout would become identical tools, if they both had that feature. Which makes me think, why not just use Docker Compose, then?
```

What's the benefit of Takeout if you can't pin a requirement?

**Comment by josecanhelp** [comment]
@ju5t starting all dependencies at once and pinning versions is exactly what docker-compose is so good at.

Can you give me an example workflow of how you think those features would be used in takeout without confusing the newcomers to docker?

**Comment by ju5t** [comment]
`takeout` will set up a new Docker container version X.Y.Z, sets up port mapping and uses a volume for data storage. It wraps around `docker run`. Which is great. Not just for newcomers, I think it can be a game changer.

Let’s say we have a simple application. It runs Laravel and we only use MySQL 5.x. We have 5 developers and they all run `takeout`. They pick MySQL 5.x and everyone’s happy.

A few weeks in we decide to add caching. I’m going for Redis, launch it with `takeout` and I am good to go. After testing it all, I commit and other developers start working on it too. How will they know which version I used? Are we adding the version to the README? Probably. The CHANGELOG is great, but isn’t helpful when we hire the next developer. I prefer not to add dependencies to the README.

The same could be said about which MySQL version we’re using.

I like some sort of version pinning. We’re pinning PHP and NPM too. Both for a good reason. I think there are two reasons to use Docker. It’s simplicity, `takeout` does that to the next level, and picking the version you need for your application.

Arguably you could say, just use Docker Compose. Not a lot of people use `Docker Compose` and I think `takeout` can fill that gap without it all coming down to a single developer who happens to know a thing or two. Your Laracon presentation felt very familiar.

I wouldn’t make it too confusing to begin with. A simple `save` command to store the containers you added into a `.takeout.json` or similar would be enough. You would only need to store the container(s), port mapping and volume, as it shouldn’t replace Docker Compose. Starting and stopping are obviously useful too. Not sure if I would use the `start` and `stop` commands for it as it could be confusing.

Knowing and pinning the volume would also make it possible to .gitignore it by the way, as every environment would be the same.

Does this clarify it better?
