### ISSUE TITLE
Install fails - illuminate/container v6.6.1

### ISSUE THREAD

**Issue by opejovic** [tightenco/takeout#63]
`composer global require tightenco/takeout` 

 Problem 1
    - Installation request for tightenco/takeout ^1.0 -> satisfiable by tightenco/takeout[v1.0.0].
    - Conclusion: remove illuminate/container v6.6.1
    - Conclusion: don't install illuminate/container v6.6.1
    - tightenco/takeout v1.0.0 requires laravel-zero/framework ^7.0 -> satisfiable by laravel-zero/framework[v7.0.0, v7.1.0, v7.2.0, v7.2.1].
    - laravel-zero/framework v7.0.0 requires illuminate/container ^7.0 -> satisfiable by illuminate/container[v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.2.0, v7.2.1, v7.2.2, v7.20.0, v7.21.0, v7.22.0, v7.22.1, v7.22.2, v7.22.3, v7.22.4, v7.23.0, v7.23.1, v7.23.2, v7.24.0, v7.25.0, v7.26.0, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].
    - laravel-zero/framework v7.1.0 requires illuminate/container ^7.0 -> satisfiable by illuminate/container[v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.2.0, v7.2.1, v7.2.2, v7.20.0, v7.21.0, v7.22.0, v7.22.1, v7.22.2, v7.22.3, v7.22.4, v7.23.0, v7.23.1, v7.23.2, v7.24.0, v7.25.0, v7.26.0, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].
    - laravel-zero/framework v7.2.0 requires illuminate/container ^7.0 -> satisfiable by illuminate/container[v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.2.0, v7.2.1, v7.2.2, v7.20.0, v7.21.0, v7.22.0, v7.22.1, v7.22.2, v7.22.3, v7.22.4, v7.23.0, v7.23.1, v7.23.2, v7.24.0, v7.25.0, v7.26.0, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].
    - laravel-zero/framework v7.2.1 requires illuminate/container ^7.0 -> satisfiable by illuminate/container[v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.2.0, v7.2.1, v7.2.2, v7.20.0, v7.21.0, v7.22.0, v7.22.1, v7.22.2, v7.22.3, v7.22.4, v7.23.0, v7.23.1, v7.23.2, v7.24.0, v7.25.0, v7.26.0, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].
    - Can only install one of: illuminate/container[v7.0.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.0.1, v6.6.1].
    - Can only install one of: illuminate/container[v7.0.2, v6.6.1].
    - Can only install one of: illuminate/container[v7.0.3, v6.6.1].
    - Can only install one of: illuminate/container[v7.0.4, v6.6.1].
    - Can only install one of: illuminate/container[v7.0.5, v6.6.1].
    - Can only install one of: illuminate/container[v7.0.6, v6.6.1].
    - Can only install one of: illuminate/container[v7.0.7, v6.6.1].
    - Can only install one of: illuminate/container[v7.0.8, v6.6.1].
    - Can only install one of: illuminate/container[v7.1.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.1.1, v6.6.1].
    - Can only install one of: illuminate/container[v7.1.2, v6.6.1].
    - Can only install one of: illuminate/container[v7.1.3, v6.6.1].
    - Can only install one of: illuminate/container[v7.10.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.10.1, v6.6.1].
    - Can only install one of: illuminate/container[v7.10.2, v6.6.1].
    - Can only install one of: illuminate/container[v7.10.3, v6.6.1].
    - Can only install one of: illuminate/container[v7.11.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.12.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.13.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.14.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.14.1, v6.6.1].
    - Can only install one of: illuminate/container[v7.15.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.16.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.16.1, v6.6.1].
    - Can only install one of: illuminate/container[v7.17.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.17.1, v6.6.1].
    - Can only install one of: illuminate/container[v7.17.2, v6.6.1].
    - Can only install one of: illuminate/container[v7.18.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.19.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.19.1, v6.6.1].
    - Can only install one of: illuminate/container[v7.2.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.2.1, v6.6.1].
    - Can only install one of: illuminate/container[v7.2.2, v6.6.1].
    - Can only install one of: illuminate/container[v7.20.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.21.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.22.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.22.1, v6.6.1].
    - Can only install one of: illuminate/container[v7.22.2, v6.6.1].
    - Can only install one of: illuminate/container[v7.22.3, v6.6.1].
    - Can only install one of: illuminate/container[v7.22.4, v6.6.1].
    - Can only install one of: illuminate/container[v7.23.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.23.1, v6.6.1].
    - Can only install one of: illuminate/container[v7.23.2, v6.6.1].
    - Can only install one of: illuminate/container[v7.24.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.25.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.26.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.3.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.4.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.5.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.5.1, v6.6.1].
    - Can only install one of: illuminate/container[v7.5.2, v6.6.1].
    - Can only install one of: illuminate/container[v7.6.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.6.1, v6.6.1].
    - Can only install one of: illuminate/container[v7.6.2, v6.6.1].
    - Can only install one of: illuminate/container[v7.7.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.7.1, v6.6.1].
    - Can only install one of: illuminate/container[v7.8.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.8.1, v6.6.1].
    - Can only install one of: illuminate/container[v7.9.0, v6.6.1].
    - Can only install one of: illuminate/container[v7.9.1, v6.6.1].
    - Can only install one of: illuminate/container[v7.9.2, v6.6.1].
    - Installation request for illuminate/container (locked at v6.6.1) -> satisfiable by illuminate/container[v6.6.1].

**Comment by mattstauffer** [comment]
@opejovic We're using the latest version of Laravel Zero and you have a global dependency that's attached to a lower version of Laravel. Can you update your other global dependencies?

Also, we're hoping to use a tool Laravel Zero exposes that allows us to bundle the install so we don't have to do that in the future.
