### ISSUE TITLE
php 7.2 support

### ISSUE THREAD

**Issue by danielebarbaro** [tightenco/takeout#74]
Hi, in several projects i had to use php 7.2 and in this specific case i'm using a Laravel 7.26.

<img width="572" alt="Screenshot 2020-08-27 at 10 33 38" src="https://user-images.githubusercontent.com/4376886/91417461-1fb25f80-e851-11ea-9b7d-ddfccc3e7043.png">

Allow a trailing comma in function calls was introduced in 7.3 [https://wiki.php.net/rfc/trailing-comma-function-calls]

**Comment by mattstauffer** [comment]
Thanks @danielebarbaro! Please let me know if you see any more issues.
