### ISSUE TITLE
False error detection: Docker Not Running

### ISSUE THREAD

**Issue by riipandi** [tightenco/takeout#79]
Hi, 

Thank you for creating another great toolkit for PHP developer. I just installed takeout, my Docker already running but got this message: `ERR  Docker is not running.`

Does Takeout need a specific container to be installed first?

<img width="846" alt="Screenshot 2020-08-28 at 09 56 13" src="https://user-images.githubusercontent.com/921834/91516137-ea6f4580-e914-11ea-8be6-59edcde960be.png">

**Comment by riipandi** [comment]
My bad!

Solved by running: `open --background -a Docker`

**Comment by Larsklopstra** [comment]
Still occurs on Linux (Ubuntu 20.04)

**Comment by mattstauffer** [comment]
@Larsklopstra Sorry for the delay; is this still an issue? Thanks!

**Comment by Larsklopstra** [comment]
Nope! I'll post my solution tomorrow when I'm at my desk 😄
