### ISSUE TITLE
Enable Xpack security in elasticsearch container

### ISSUE THREAD

**Issue by ian-nisbet** [tightenco/takeout#85]
Is there a simple way to enable xpack security inside the elasticsearch container? 
Perhaps there can be a choice of enabling elasticsearch-with-ssl and elasticsearch-without-ssl.

**Comment by josecanhelp** [comment]
In the current state, there isn't a way to do this simply. However, this brings up a great conversation about how we can either customize images (adding a build layer?) or pass config files into the container during the run process.

I created a backlog issue for this in #91. 

Thanks for taking Takeout for a spin!
