### ISSUE TITLE
Build new tagged build to include added services

### ISSUE THREAD

**Issue by s1rc** [tightenco/takeout#90]
Currently tag 1.1.0 doesn't include the new services: Minio and InfluxDB. 

We can checkout `dev-main` in composer and `php app:build` but it would be great to have the new services included in the compiled binary with a new tag, i.e. 1.2.0.

**Comment by mattstauffer** [comment]
https://github.com/tightenco/takeout/releases/tag/v1.2.2

Apologies, life got crazy for a bit. :)
