### ISSUE TITLE
Errors after update to latest version

### ISSUE THREAD

**Issue by wrtisans** [tightenco/takeout#97]
i'm having this errors everywhere where i wrote takeout, im using php homebrew and the problem is only with this package 

PHP Warning:  require_once(phar:///Users/ds/.composer/vendor/tightenco/takeout/builds/takeout/bootstrap/app.php): failed to open stream: phar error: "bootstrap/app.php" is not a file in phar "/Users/ds/.composer/vendor/tightenco/takeout/builds/takeout" in phar:///Users/ds/.composer/vendor/tightenco/takeout/builds/takeout/takeout on line 19

Warning: require_once(phar:///Users/ds/.composer/vendor/tightenco/takeout/builds/takeout/bootstrap/app.php): failed to open stream: phar error: "bootstrap/app.php" is not a file in phar "/Users/ds/.composer/vendor/tightenco/takeout/builds/takeout" in phar:///Users/ds/.composer/vendor/tightenco/takeout/builds/takeout/takeout on line 19
PHP Fatal error:  require_once(): Failed opening required 'phar:///Users/ds/.composer/vendor/tightenco/takeout/builds/takeout/bootstrap/app.php' (include_path='.:/usr/local/Cellar/php/7.4.9/share/php/pear') in phar:///Users/ds/.composer/vendor/tightenco/takeout/builds/takeout/takeout on line 19

Fatal error: require_once(): Failed opening required 'phar:///Users/ds/.composer/vendor/tightenco/takeout/builds/takeout/bootstrap/app.php' (include_path='.:/usr/local/Cellar/php/7.4.9/share/php/pear') in phar:///Users/ds/.composer/vendor/tightenco/takeout/builds/takeout/takeout on line 19

**Comment by adam-apg** [comment]
@wrtisans Same issue for me.  I was able to get things working by reverting back to 1.2.0.

**Comment by mattstauffer** [comment]
`1.2.0` is not actually a new build, sadly. It was a mistake.

Let me take a look and see if I can solve this one.
